# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -q update
  - sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
  - R -e 'install.packages("devtools")'

brew_packages:
  - gdal

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran
