---
title: "Getting Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Maps and capacity data

```{r setup}
devtools::load_all()
library(tidyverse)
library(patchwork)

here::i_am("vignettes/getting-started.Rmd")
options("arear.cache.dir"=here::here("data-raw/cache"))

#library(arear)
```

```{r}
# https://api.coronavirus.data.gov.uk/v2/data?areaType=nhsTrust&metric=newAdmissions&format=csv
arear::listStandardMaps()
map = arear::getMap("CTRY19")
nhshospitals = arear::surgecapacity %>% dplyr::filter(sector == "NHS Sector")

```

```{r}
ggplot()+geom_sf(data=map)+geom_sf(data=nhshospitals,aes(colour=tier1))
```


# Containment

```{r}
nhser = arear::getMap("NHSER20")
hospitalId2nhser = arear::getContainedIn(nhshospitals %>% group_by(hospitalId, hospitalName), nhser %>% group_by(code,name))

hospitalsByNhser = nhshospitals %>% inner_join(hospitalId2nhser,by=c("hospitalId","hospitalName"))
ggplot()+geom_sf(data=nhser)+geom_sf(data = hospitalsByNhser,aes(colour=name))
```

# Intersection

```{r}
phec = arear::getMap("PHEC16")
phecNhser = arear::getIntersection(phec,nhser)

p1 = ggplot()+geom_sf(data=nhser,colour="red")
p2 = ggplot()+geom_sf(data=phec,colour="blue")
p3 = ggplot()+geom_sf(data=phecNhser)

p1+p2+p3

tmp = phecNhser %>% as_tibble() %>% mutate(frac = intersectionArea/area.x)
tmp %>% group_by(name.x) %>% summarise(cov = sum(frac))

```


```{r}
nhserBeds = hospitalsByNhser %>% as_tibble() %>% group_by(code,name) %>% summarise(
  acuteBeds = sum(acuteBeds),
  hduBeds = sum(hduBeds)
) %>% pivot_longer(cols=c(acuteBeds,hduBeds),names_to="type",values_to="beds")

```

# Areal interpolation

```{r}

phecBeds = nhserBeds %>% group_by(type) %>% arear::interpolateByArea(inputShape = nhser,by="code", interpolateVar = beds, outputShape = phec %>% group_by(name,code))

phecBeds %>% group_by(type) %>% summarise(beds = sum(beds))
nhserBeds %>% group_by(type) %>% summarise(beds = sum(beds))

```

# Geography as network

```{r}
lad = arear::getMap("LAD19")

tmp = arear::surgecapacity %>% group_by(hospitalId, hospitalName, acuteBeds) %>% arear::getContainedIn(lad %>% group_by(code,name)) %>% group_by(code,name) %>% summarise(beds = sum(acuteBeds))
nodes = lad %>% left_join(tmp,by=c("code","name")) %>% mutate(beds=ifelse(is.na(beds),0,beds)) %>% ungroup()
edges = lad %>% arear::createNeighbourNetwork() 

graph = tidygraph::tbl_graph(nodes = nodes,edges=edges,node_key = "code")

#graph %>% tidygraph::activate(edges) %>% mutate(weight = 1+200/(tidygraph::.N()$beds[from]*tidygraph::.N()$beds[to]))

  
ggraph::ggraph(graph, layout="kk")+
  ggraph::geom_edge_link() + 
  ggraph::geom_node_point(aes(size=beds))


```

# Preview a map with points of interest overlaid

```{r}
devtools::load_all()
arear::preview(lad,
      poi=nhshospitals, 
      poiLabelGlue = "{hospitalName}",
      poiPopupGlue = "<b>{hospitalName}</b><ul><li>{trustName}</li><li>hdu: {hduBeds}</li><li>acute: {acuteBeds}</li></ul>"
)

```

```{r}


apiTrusts = readr::read_csv("https://api.coronavirus.data.gov.uk/v2/data?areaType=nhsTrust&metric=hospitalCases&format=csv&release=2021-03-01")

# There are quite a few mental health, community, specialist and children's trusts that we do not as yet have sensible capacity data for, and although they report COVID
# cases these are essentially incidental to the care of the patient.
# However at last look this list also includes NHS Nightingale hospitals which we have not included
# apiTrusts %>% select(areaCode,areaName) %>% distinct() %>% anti_join(arear::surgecapacity, by = c("areaCode"="trustId")) %>% View()

# The API output includes only NHS trusts in England
# there should be no NHS Trusts in this data that do not appear in the API.
# arear::surgecapacity %>% filter(nation == "England" & sector == "NHS Sector") %>% anti_join(apiTrusts, by = c("trustId"="areaCode")) %>% View()

sup = arear::surgecapacity %>% semi_join(apiTrusts, by = c("trustId"="areaCode"))
dem = arear::uk2019demographicsmap %>% filter(code %>% stringr::str_starts("E")) %>% left_join(arear::uk2019adultpopulation %>% select(-name,-codeType), by="code")

catchment = arear::createCatchment(
  supplyShape = sup, 
  supplyIdVar = trustId, 
  supplyVar = acuteBeds,
  demandShape = dem,
  demandIdVar = code, 
  demandVar = population,
  outputMap = TRUE
)

# A general aim of the algorithm is to try and distribute supply to demand as evenly as possible given geographical constraint.
ggplot(catchment$map %>% mutate(bedsPer100K = acuteBeds / (population/100000)))+geom_sf(mapping = aes(fill = bedsPer100K))

# catchment$map %>% glimpse()


```
