# Standalone file: do not edit by hand
# Source: https://github.com/terminological/ggrrr/blob/HEAD/R/standalone-singleton.R
# Generated by: usethis::use_standalone("terminological/ggrrr", "singleton")
# ----------------------------------------------------------------------
#
# ---
# repo: terminological/ggrrr
# file: standalone-singleton.R
# last-updated: '2025-09-18'
# license: https://unlicense.org
# imports: rlang
# ---

#' A once only evaluation function generator
#'
#' This function can be used in a package to create a package local variable
#' that is calculated once on first use and stored for the rest of the session.
#' If the expression throws an uncaught error the value is not stored. The
#' expression is evaluated in the environment it is first called in.
#'
#' @param expr an expression the value of which is to be cached.
#' @param on_error a function that takes a single value (the error) and
#'   handles or rethrows it.
#'
#' @returns the result of expr.
#'
#' @noRd
#' @concept cache
#'
#' @examples
#'
#' fixed_rnorm = .singleton(rnorm(10))
#' a = fixed_rnorm()
#' b = fixed_rnorm()
#' identical(a,b)
#'
.singleton = function(
  expr,
  on_error = function(e) {
    stop("Initialising value failed:", e, call. = FALSE)
  }
) {
  b = rlang::enexpr(expr)
  on_error = rlang::as_function(on_error)
  value = NULL
  function() {
    if (!is.null(value)) {
      return(value)
    }
    tmp = tryCatch(
      eval(b, envir = rlang::caller_env()),
      error = on_error
    )
    value <<- tmp
    return(tmp)
  }
}
