# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ${{ matrix.config.os }}

    continue-on-error: false

    name: ${{ matrix.config.os }} R:(${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: '4.1.0', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: macOS-11, r: '4.1.0'}
          - {os: windows-2022, r: '4.2.0'}
          - {os: ubuntu-20.04, r: '3.6.1', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: '4.2.0', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'devel', http-user-agent: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL on macOS
        if: runner.os == 'macOS'
        run: |
          brew install gdal proj geos

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install GDAL on linux
        if: runner.os == 'Linux'
        # run: sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && sudo apt-get -q update && sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev && sudo ldconfig
        run: sudo apt install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libfontconfig1-dev r-cran-sf r-cran-raster r-cran-rjava
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual","--no-build-vignettes")'
