# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL on macOS
        if: runner.os == 'macOS'
        run: |
          brew install gdal proj geos
      - name: Install GDAL on linux
        if: runner.os == 'Linux'
        run: sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && sudo apt-get -q update && sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual","--no-build-vignettes")'
